# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_take.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(296, 203)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Pretendard")
        font.setPointSize(6)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("QWidget{\n"
"font-family: Pretendard;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: transparent;\n"
"font-size: 30px;\n"
"text-align: center;\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.spinBox = QtWidgets.QSpinBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Pretendard")
        font.setPointSize(-1)
        font.setBold(False)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("border: 2px solid #212529;\n"
"    background-color: #fff;\n"
"    color: #212529;\n"
"    font-weight: 500;\n"
"    font-size: 40px;\n"
"    border-top-left-radius: 0.3rem;\n"
"    border-top-right-radius: 0.3rem;")
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_4.setStyleSheet("QWidget{\n"
"font-family: Pretendard;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_check = QtWidgets.QPushButton(self.widget_4)
        self.pb_check.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Pretendard")
        font.setPointSize(-1)
        font.setBold(False)
        self.pb_check.setFont(font)
        self.pb_check.setStyleSheet("border: 2px solid #212529;\n"
"    background-color: #fff;\n"
"    color: #212529;\n"
"    font-weight: 500;\n"
"    font-size: 20px;\n"
"    border-top-left-radius: 0.3rem;\n"
"    border-top-right-radius: 0.3rem;")
        self.pb_check.setObjectName("pb_check")
        self.horizontalLayout_2.addWidget(self.pb_check, 0, QtCore.Qt.AlignHCenter)
        self.pb_cancel = QtWidgets.QPushButton(self.widget_4)
        self.pb_cancel.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Pretendard")
        font.setPointSize(-1)
        font.setBold(False)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setStyleSheet("border: 2px solid #212529;\n"
"    background-color: #fff;\n"
"    color: #212529;\n"
"    font-weight: 500;\n"
"    font-size: 20px;\n"
"    border-top-left-radius: 0.3rem;\n"
"    border-top-right-radius: 0.3rem;")
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_4)

        self.retranslateUi(Dialog)
        self.pb_check.clicked.connect(Dialog.accept) # type: ignore
        self.pb_cancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "입고"))
        self.label.setText(_translate("Dialog", "상품코드:"))
        self.pb_check.setText(_translate("Dialog", "확인"))
        self.pb_cancel.setText(_translate("Dialog", "취소"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
