# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_membership.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(337, 553)
        Dialog.setStyleSheet("font-family: Pretendard;\n"
"background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalFrame = QtWidgets.QFrame(self.frame)
        self.verticalFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lb_profile_img = QtWidgets.QLabel(self.verticalFrame)
        self.lb_profile_img.setMinimumSize(QtCore.QSize(150, 150))
        self.lb_profile_img.setStyleSheet("border: 2px solid #00b3ce;\n"
"border-radius: 75;")
        self.lb_profile_img.setText("")
        self.lb_profile_img.setObjectName("lb_profile_img")
        self.verticalLayout_7.addWidget(self.lb_profile_img)
        self.pb_regist_img = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_regist_img.sizePolicy().hasHeightForWidth())
        self.pb_regist_img.setSizePolicy(sizePolicy)
        self.pb_regist_img.setMinimumSize(QtCore.QSize(100, 30))
        self.pb_regist_img.setStyleSheet("background: #00b3ce;\n"
"    color: #ffffff;\n"
"    font-weight: 500;\n"
"border-radius: 15px;\n"
"    font-size: 20px;")
        self.pb_regist_img.setObjectName("pb_regist_img")
        self.verticalLayout_7.addWidget(self.pb_regist_img, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.verticalFrame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(50, 0, 50, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.le_id = QtWidgets.QLineEdit(self.frame_2)
        self.le_id.setStyleSheet("QLineEdit{\n"
"border: none; \n"
"border-bottom: 2px solid #00b3ce;\n"
"background-color: transparent;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.le_id.setText("")
        self.le_id.setObjectName("le_id")
        self.verticalLayout_5.addWidget(self.le_id)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(Dialog)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lb_warning_id = QtWidgets.QLabel(self.frame_8)
        self.lb_warning_id.setText("")
        self.lb_warning_id.setObjectName("lb_warning_id")
        self.verticalLayout_9.addWidget(self.lb_warning_id, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(50, 0, 50, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.le_pw = QtWidgets.QLineEdit(self.frame_3)
        self.le_pw.setStyleSheet("QLineEdit{\n"
"border: none; \n"
"border-bottom: 2px solid #00b3ce;\n"
"background-color: transparent;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.le_pw.setText("")
        self.le_pw.setObjectName("le_pw")
        self.verticalLayout_6.addWidget(self.le_pw)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_7 = QtWidgets.QFrame(Dialog)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lb_warning_pw = QtWidgets.QLabel(self.frame_7)
        self.lb_warning_pw.setText("")
        self.lb_warning_pw.setObjectName("lb_warning_pw")
        self.verticalLayout_8.addWidget(self.lb_warning_pw, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_nick = QtWidgets.QLineEdit(self.frame_5)
        self.le_nick.setStyleSheet("QLineEdit{\n"
"border: none; \n"
"border-bottom: 2px solid #00b3ce;\n"
"background-color: transparent;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.le_nick.setText("")
        self.le_nick.setObjectName("le_nick")
        self.horizontalLayout.addWidget(self.le_nick)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(Dialog)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_warning_nick = QtWidgets.QLabel(self.frame_6)
        self.lb_warning_nick.setText("")
        self.lb_warning_nick.setObjectName("lb_warning_nick")
        self.verticalLayout_2.addWidget(self.lb_warning_nick, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_join = QtWidgets.QPushButton(self.frame_4)
        self.pb_join.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Pretendard")
        font.setPointSize(-1)
        font.setBold(False)
        self.pb_join.setFont(font)
        self.pb_join.setStyleSheet("border: 2px solid #00b3ce;\n"
"    background-color: #fff;\n"
"    color: #00b3ce;\n"
"    font-weight: 500;\n"
"border-radius: 20px;\n"
"    font-size: 20px;\n"
"\n"
"")
        self.pb_join.setObjectName("pb_join")
        self.horizontalLayout_2.addWidget(self.pb_join, 0, QtCore.Qt.AlignHCenter)
        self.pb_member = QtWidgets.QPushButton(self.frame_4)
        self.pb_member.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Pretendard")
        font.setPointSize(-1)
        font.setBold(False)
        self.pb_member.setFont(font)
        self.pb_member.setStyleSheet("border: 2px solid #00b3ce;\n"
"    background-color: #fff;\n"
"    color: #00b3ce;\n"
"    font-weight: 500;\n"
"border-radius: 20px;\n"
"    font-size: 20px;\n"
"\n"
"")
        self.pb_member.setObjectName("pb_member")
        self.horizontalLayout_2.addWidget(self.pb_member, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_regist_img.setText(_translate("Dialog", "사진등록"))
        self.pb_join.setText(_translate("Dialog", "회원가입"))
        self.pb_member.setText(_translate("Dialog", "취소"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
