# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(613, 396)
        Dialog.setStyleSheet("font-family: Pretendard;\n"
"background-color: rgb(255, 255, 255);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setStyleSheet("QWidget{\n"
"font-family: Pretendard;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid #164DCA;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"border-bottom:none;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border: none; \n"
"border-bottom: 2px solid #164DCA;\n"
"background-color: transparent;\n"
"font-size: 20px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 20px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setStyleSheet("border: none;\n"
"border-radius: 0;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.img = QtWidgets.QLabel(self.widget)
        self.img.setMinimumSize(QtCore.QSize(140, 160))
        self.img.setMaximumSize(QtCore.QSize(140, 160))
        self.img.setStyleSheet("border: 2px dashed  #164DCA;")
        self.img.setObjectName("img")
        self.verticalLayout.addWidget(self.img)
        self.pb_load = QtWidgets.QPushButton(self.widget)
        self.pb_load.setStyleSheet("QPushButton{\n"
"background: #164DCA;\n"
"box-shadow: 0px 2px 12px rgb(25 25 25 / 16%);\n"
"align-items: center;\n"
"color: #fff;\n"
"font-weight: 600;\n"
"font-size: 20px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"}")
        self.pb_load.setObjectName("pb_load")
        self.verticalLayout.addWidget(self.pb_load, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setStyleSheet("QWidget{\n"
"border: none;\n"
"border-radius: 20;\n"
"    background-color: rgb(247, 247, 247);\n"
"border: 2px solid #164DCA;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border: none; \n"
"border-bottom: 2px solid #164DCA;\n"
"background-color: transparent;\n"
"font-size: 20px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 20px;\n"
"border:none;\n"
"border-radius:0;\n"
"font-weight:300;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(10, 15, 15, 15)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.inventory = QtWidgets.QLineEdit(self.widget_2)
        self.inventory.setObjectName("inventory")
        self.gridLayout.addWidget(self.inventory, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.sales_unit_price = QtWidgets.QLineEdit(self.widget_2)
        self.sales_unit_price.setObjectName("sales_unit_price")
        self.gridLayout.addWidget(self.sales_unit_price, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 2, 1)
        self.purchase_unit_price = QtWidgets.QLineEdit(self.widget_2)
        self.purchase_unit_price.setObjectName("purchase_unit_price")
        self.gridLayout.addWidget(self.purchase_unit_price, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.safety_inventory = QtWidgets.QLineEdit(self.widget_2)
        self.safety_inventory.setObjectName("safety_inventory")
        self.gridLayout.addWidget(self.safety_inventory, 7, 1, 2, 1)
        self.name = QtWidgets.QLineEdit(self.widget_2)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 3, 1, 1, 1)
        self.brand = QtWidgets.QLineEdit(self.widget_2)
        self.brand.setObjectName("brand")
        self.gridLayout.addWidget(self.brand, 2, 1, 1, 1)
        self.code = QtWidgets.QLineEdit(self.widget_2)
        self.code.setObjectName("code")
        self.gridLayout.addWidget(self.code, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.type = QtWidgets.QLineEdit(self.widget_2)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setStyleSheet("QWidget{\n"
"font-family: Pretendard;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid #164DCA;\n"
"border-bottom-left-radius: 15px;\n"
"border-bottom-right-radius: 15px;\n"
"border-top:none;\n"
"}\n"
"QPushButton{\n"
"background: #164DCA;\n"
"box-shadow: 0px 2px 12px rgb(25 25 25 / 16%);\n"
"align-items: center;\n"
"color: #fff;\n"
"font-weight: 600;\n"
"font-size: 20px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_save = QtWidgets.QPushButton(self.widget_4)
        self.pb_save.setMinimumSize(QtCore.QSize(75, 30))
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_2.addWidget(self.pb_save, 0, QtCore.Qt.AlignHCenter)
        self.pb_reset = QtWidgets.QPushButton(self.widget_4)
        self.pb_reset.setMinimumSize(QtCore.QSize(75, 30))
        self.pb_reset.setObjectName("pb_reset")
        self.horizontalLayout_2.addWidget(self.pb_reset, 0, QtCore.Qt.AlignHCenter)
        self.pb_close = QtWidgets.QPushButton(self.widget_4)
        self.pb_close.setMinimumSize(QtCore.QSize(75, 30))
        self.pb_close.setObjectName("pb_close")
        self.horizontalLayout_2.addWidget(self.pb_close, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.code, self.type)
        Dialog.setTabOrder(self.type, self.brand)
        Dialog.setTabOrder(self.brand, self.name)
        Dialog.setTabOrder(self.name, self.purchase_unit_price)
        Dialog.setTabOrder(self.purchase_unit_price, self.sales_unit_price)
        Dialog.setTabOrder(self.sales_unit_price, self.inventory)
        Dialog.setTabOrder(self.inventory, self.safety_inventory)
        Dialog.setTabOrder(self.safety_inventory, self.pb_load)
        Dialog.setTabOrder(self.pb_load, self.pb_save)
        Dialog.setTabOrder(self.pb_save, self.pb_reset)
        Dialog.setTabOrder(self.pb_reset, self.pb_close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.img.setText(_translate("Dialog", "이미지"))
        self.pb_load.setText(_translate("Dialog", "사진등록"))
        self.label_4.setText(_translate("Dialog", "분류"))
        self.label_6.setText(_translate("Dialog", "구매단가"))
        self.label_8.setText(_translate("Dialog", "재고"))
        self.label_3.setText(_translate("Dialog", "브랜드"))
        self.label_9.setText(_translate("Dialog", "안전재고"))
        self.label_2.setText(_translate("Dialog", "상품코드"))
        self.label_7.setText(_translate("Dialog", "판매단가"))
        self.label_5.setText(_translate("Dialog", "상품명"))
        self.pb_save.setText(_translate("Dialog", "저장"))
        self.pb_reset.setText(_translate("Dialog", "다시작성"))
        self.pb_close.setText(_translate("Dialog", "닫기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
